version = 1

[[annotations]]
path = "**/*"
SPDX-FileCopyrightText = [
  "2025 AFCMS <afcm.contact@gmail.com>",
  "2025 AKArien0 <emilien.dessarps@gmail.com>",
  "2025 Roceann <raphael.malet2005@gmail.com>",
  "2025 weyrito <thomasfouquet76@gmail.com>",
]
SPDX-License-Identifier = "GPL-3.0-or-later"
