---
name: Marp

on:
  push:
    branches: ["master"]
    paths:
      - "presentation/presentation_fr-FR.md"
      - ".github/workflows/marp.yml"
  pull_request:
    branches: ["master"]
    paths:
      - "presentation/presentation_fr-FR.md"
      - ".github/workflows/marp.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS/Jod
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      # https://github.com/marp-team/marp-cli
      - name: Install Marp CLI
        run: pnpm install -g @marp-team/marp-cli

      - name: Build PDF Slide Deck
        run: marp --pdf ./presentation/presentation_fr-FR.md

      - name: Upload PDF Slide Deck
        uses: actions/upload-artifact@v4
        with:
          name: presentation_fr-FR
          path: ./presentation/presentation_fr-FR.pdf
